services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: dockerfile
    image: mariadb:v1
    container_name: mariadb
    restart: always
    env_file:
      - ./.env  # Correctly placed under the mariadb service
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: dockerfile
    image: wordpress:v1
    container_name: wordpress
    restart: always
    env_file:
      - ./.env  # Correctly placed under the wordpress service
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network

  nginx:
    build:
      context: ./requirements/nginx  # Assuming the Dockerfile for Nginx is in the same directory
      dockerfile: dockerfile  # Specify the Dockerfile name if it's not "Dockerfile"
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"  # Expose HTTPS
    volumes:
      - wordpress_data:/var/www/html  # Ensure this is correctly listed as a volume
    networks:
      - wp_network

volumes:
  mariadb_data:
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mbdata
  wordpress_data:
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/wdata

networks:
  wp_network:
