# Use the official MariaDB base image
FROM debian:bullseye

# Update package list and install MariaDB server and client
RUN apt-get update && \
    apt-get install -y mariadb-server mariadb-client && \
    apt-get clean

# Copy the .sh and .sql files to the /var/local/bin/ directory
COPY ./tools/script.sh /var/local/bin/

# Make sure the MariaDB daemon and script have execution permissions
RUN chmod +x /var/local/bin/script.sh

# Command to run MariaDB and listen on all IPV4 addresses
CMD ["/var/local/bin/script.sh"]