# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Perform all operations in a single RUN command
RUN apt-get update && \
    apt-get install -y openssl && \
    apt-get clean && \
    mkdir /etc/nginx/ssl && \
    cd /etc/nginx/ssl && \
    openssl genrsa -out /etc/nginx/ssl/mysite.key 2048 && \
    openssl req -new -key /etc/nginx/ssl/mysite.key -out /etc/nginx/ssl/mysite.csr \
        -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=ohaimad.42.fr" && \
    openssl x509 -req -days 365 -in /etc/nginx/ssl/mysite.csr -signkey /etc/nginx/ssl/mysite.key -out /etc/nginx/ssl/mysite.csr
 
# Copy your custom Nginx configuration file, if you have one
COPY nginx.conf /etc/nginx/nginx.conf

# # Expose port 80 to the outside world
EXPOSE 443

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
